#!/bin/bash

. `dirname $0`/functions

option	bin		reserved_option	/usr/sbin/crond
option	cmdline		reserved_option	'$bin'

pidfile=/var/run/cron.pid
crontab=/etc/crontab
crontabdir=/var/spool/cron

function fct_pre_start {
   if [ ! -d $crontabdir] ; then
       mkdir -p -m 750 $crontabdir || return 1
   fi
}

load_config
