#!/bin/bash 

. `dirname $0`/functions

option keymap	standard_option	us
option keyrate	standard_option	30

function do_start {
   loadkeys $opt_keymap
   kbdrate -r $opt_keyrate </dev/tty0
}

function do_stop {
   loadkeys us
}

load_config

