#!/bin/bash

. `dirname $0`/functions

option	type		standard_option	ps2
option	device		standard_option	/dev/mouse
option	bin		reserved_option	/usr/sbin/gpm
option	procname	reserved_option	gpm
option	cmdline		reserved_option	'$bin -t $opt_type -m $opt_device'
option	pidfile		reserved_option	/var/run/gpm.pid

# gpm is buggy, it doesn't close its std* before forking, so the startup
# script hang at boot time because it hogs the terminal.
function fct_pre_start {
   #exec 10>&0 11>&1 12>&2
   exec </dev/null >&0 2>&0
}

function fct_pre_stop {
   $cmdline -k >/dev/null 2>&1
}

load_config
