#!/bin/bash

. `dirname $0`/functions

STOP_FIRST_WITH=KILL

option	bin	reserved_option	/usr/sbin/sshd
option	cmdline	reserved_option	'$bin -p $opt_port -f $opt_config -h $opt_hostkey'
option	port	standard_option	22
option	config	standard_option	/etc/ssh/sshd_config
option	hostkey	standard_option	/etc/ssh/ssh_host_key

# assign default values to options and variables before parsing the cfg file
function fct_end_section {
    valueof $opt_config HostKey > /dev/null ; opt_hostkey=${REPLY:-$opt_hostkey}
    valueof $opt_config PidFile > /dev/null ; pidfile=${REPLY:-$pidfile}
}

load_config

