#!/bin/bash
cfgfile=$1
. /sbin/init.d/functions -f $cfgfile --list_sections|(last=;while read svc rest; do if [ "$svc" != "$last" ]; then /sbin/init.d/$svc -f $cfgfile --auto start </dev/null; fi; last=$svc; done)
